# Generated by Django 4.1.3 on 2022-11-30 01:17

import checkin_images.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('check_ins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=checkin_images.models.CheckInImage.set_upload_path)),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('check_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='check_ins.checkin')),
            ],
        ),
    ]
