# Generated by Django 4.1.3 on 2022-12-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check_ins', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['-created_date']},
        ),
        migrations.AlterField(
            model_name='checkin',
            name='trainer_feedback',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='weekly_review',
            field=models.CharField(max_length=255),
        ),
    ]
