# Generated by Django 4.1.3 on 2022-12-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'ordering': ['assigned_day']},
        ),
    ]
