# Generated by Django 4.1.3 on 2022-12-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training_plans', '0002_alter_trainingplan_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingplan',
            name='weekly_workout_days',
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='calories',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='carbs',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='fats',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingplan',
            name='protein',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
