# Generated by Django 4.1.3 on 2022-11-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0002_rename_request_clientrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientrequest',
            name='response',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientrequest',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (0, 'Closed')], default=1),
        ),
    ]
