# Generated by Django 4.1.3 on 2022-12-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client_requests', '0003_clientrequest_response_clientrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientrequest',
            options={'ordering': ['-created_date']},
        ),
    ]
